repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: mypy
        types: [python]
        args: ["."]
        stages: [pre-commit]
      - id: autoflake
        name: autoflake
        language: system
        entry: autoflake
        types: [python]
        args: ["--remove-unused-variables", "--remove-all-unused-imports", "-i", "-r", "."]
        stages: [pre-commit]