version: '3.8'
services:
  app:
    image: listing_service
    build: .
    ports:
      - "80:80"
    depends_on:
      - "db"

  db:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

