replicaCount: @replicaCount@

serverImage: @serverImage@
serverContainerPort: @serverContainerPort@

service:
  name: @service_name@
  port: @service_port@
  targetPort: @service_targetPort@

ingress:
  enabled: @ingress_enabled@
  host: @ingress_host@
  path: "@ROOT_PATH@"
  port: @ingress_port@

autoscaling:
  enabled: @autoescaling_enabled@
  minReplicas: @autoescaling_minReplicas@
  maxReplicas: @autoescaling_maxReplicas@
  targetCPUUtilizationPercentage: @autoescaling_targetCPUUtilizationPercentage@
