replicaCount: @replicaCount@

serverImage: @serverImage@
serverContainerPort: @serverContainerPort@

service:
  name: @serverServiceName@
  port: @serverServicePort@
  targetPort: @serverServiceTargetPort@

ingress:
  enabled: @ingress_enabled@
  host: @ingress_host@
  path: "@SERVER_ROOT_PATH@"
  port: @serverIngressPort@

autoscaling:
  enabled: @autoescaling_enabled@
  minReplicas: @autoescaling_minReplicas@
  maxReplicas: @autoescaling_maxReplicas@
  targetCPUUtilizationPercentage: @autoescaling_targetCPUUtilizationPercentage@
